### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by xlwoon** [ncabatoff/zfs-exporter#2]
Hi,

I'm having trouble compiling your zfs exporter.
`$ go test` in the zfs-exporter directory yields

> \# github.com/bicomsystems/go-libzfs
> could not determine kind of name for C.boolean_t
> could not determine kind of name for C.clear_last_error
> could not determine kind of name for C.libzfs_errno
> could not determine kind of name for C.libzfs_error_description
> could not determine kind of name for C.libzfs_handle_ptr
> could not determine kind of name for C.libzfs_init
> \# github.com/ncabatoff/go-libzfs
> could not determine kind of name for C.boolean_t
> could not determine kind of name for C.clear_last_error
> could not determine kind of name for C.libzfs_errno
> could not determine kind of name for C.libzfs_error_description
> could not determine kind of name for C.libzfs_init
> FAIL    github.com/ncabatoff/go-libzfs [build failed]

I have a similar problem working with the bicomsystem's libzfs (which this repo is forked from)

Am I missing something big somewhere?

My system:
Fedora 24, kernel 4.10.11
go-1.6.4 (can't downgrade via package management system to 1.4, so probably not the way to go)
zfs-0.7.0-rc3 and libzfs2 installed and source dir linked to gopath

Thanks!
Michael

**Comment by ncabatoff** [comment]
I assume you that you have libzfs2-devel installed, else I think you'd get a missing include file error.

I haven't tried zfs 0.7, if 0.6 is available on Fedora 24 I suggest you try that.

I'll try to make some time to spin up a Fedora VM and give it a try myself, but that's not likely to happen until this weekend.

**Comment by xlwoon** [comment]
I had a little bit more of a crack at it, and it turned out that both of:
-missing libzfs2-devel
-using 0.7.0-rc rather than 0.6.x
were problems. Once I had libzfs2-devel, the missing include / could not determine error names disappeared:

> 20:55 $ go test
> \# github.com/bicomsystems/go-libzfs
> ../../bicomsystems/go-libzfs/zpool.c: In function ‘read_zpool_property’:
> ../../bicomsystems/go-libzfs/zpool.c:199:6: error: too few arguments to function ‘zpool_get_prop’
>   r = zpool_get_prop(zh, prop,
>       ^~~~~~~~~~~~~~
> In file included from ../../bicomsystems/go-libzfs/zpool.c:5:0:
> /usr/include/libzfs/libzfs.h:297:12: note: declared here
>  extern int zpool_get_prop(zpool_handle_t *, zpool_prop_t, char *,
>             ^~~~~~~~~~~~~~
> FAIL    github.com/ncabatoff/go-libzfs [build failed]

When I downgraded to 0.6.5.9, however, I got this:

> 21:02 $ go test
> TEST PoolCreate ... 
> fatal error: unexpected signal during runtime execution
> [signal 0xb code=0x1 addr=0x4 pc=0x7f7d8482c0ed]
> 
> runtime stack:
> runtime.throw(0x5e5740, 0x2a)
>         /usr/lib/golang/src/runtime/panic.go:547 +0x90
> runtime.sigpanic()
>         /usr/lib/golang/src/runtime/sigpanic_unix.go:12 +0x5a
> 
> goroutine 5 [syscall, locked to thread]:
> runtime.cgocall(0x529170, 0xc42003b4f8, 0x10000c400000000)
>         /usr/lib/golang/src/runtime/cgocall.go:123 +0x11b fp=0xc42003b4c0 sp=0xc42003b490
> github.com/bicomsystems/go-libzfs._Cfunc_zpool_list_open(0x0, 0x1330370, 0x0)
>         ??:0 +0x42 fp=0xc42003b4f8 sp=0xc42003b4c0
> github.com/bicomsystems/go-libzfs.PoolOpen(0x5b0910, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /home/woon/go/src/github.com/bicomsystems/go-libzfs/zpool.go:135 +0x168 fp=0xc42003b550 sp=0xc42003b4f8
> github.com/ncabatoff/go-libzfs_test.zpoolTestPoolCreate(0xc42009c000)
>         /home/woon/go/src/github.com/ncabatoff/go-libzfs/zpool_test.go:71 +0x81 fp=0xc42003bf58 sp=0xc42003b550
> github.com/ncabatoff/go-libzfs_test.Test(0xc42009c000)
>         /home/woon/go/src/github.com/ncabatoff/go-libzfs/a_test.go:11 +0x25 fp=0xc42003bf68 sp=0xc42003bf58
> testing.tRunner(0xc42009c000, 0x878fb0)
>         /usr/lib/golang/src/testing/testing.go:473 +0x98 fp=0xc42003bfa0 sp=0xc42003bf68
> runtime.goexit()
>         /usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc42003bfa8 sp=0xc42003bfa0
> created by testing.RunTests
>         /usr/lib/golang/src/testing/testing.go:582 +0x892
> 
> goroutine 1 [chan receive]:
> testing.RunTests(0x5f56e8, 0x878fb0, 0x1, 0x1, 0x7f7d84c1c001)
>         /usr/lib/golang/src/testing/testing.go:583 +0x8d2
> testing.(*M).Run(0xc42004bef8, 0x15)
>         /usr/lib/golang/src/testing/testing.go:515 +0x81
> main.main()
>         github.com/ncabatoff/go-libzfs/_test/_testmain.go:54 +0x117
> 
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
>         /usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1
> exit status 2
> FAIL    github.com/ncabatoff/go-libzfs  0.008s

(which is far beyond me unfortunately)

Are you also building on a Red Hat based distribution? Might my kernel be too new or too out of date?

Aside: do you have any plans to update this for 0.7.0 once it comes out? I think they're getting pretty close to the release.

Thanks for taking the time to reply to me,
Michael

**Comment by ncabatoff** [comment]
I don't routinely build on RH based systems, but I do at times.  I'll try to have a look at that and the 0.7.0 release this weekend. Note that I'm not the author of go-libzfs, I just made a fork to fix some issues and haven't yet got around to updating zfs-exporter to use the upstream version.

**Comment by xlwoon** [comment]
Yes, I understand that this is a fork, I'm mostly interested in using your zfs-exporter, but unable to compile it because of problems with go-libzfs.

Are you building on Debian then?

**Comment by ncabatoff** [comment]
I'm building on Ubuntu 16.04.  By the way, while I was working on issue #3 I happened to run the go-libzfs tests without root privs.  It produced the same error as you got, i.e.

```
TEST PoolCreate ...
fatal error: unexpected signal during runtime execution
```

Try running the tests again as root.

**Comment by ncabatoff** [comment]
I've pushed a changeset that installs ZFS and zfs-exporter on a Fedora25 VM via Vagrant and Ansible.  I'm going to close this issue because I'm satisfied that at least with ZFS 0.6 it works fine.  I'll worry about 0.7 once it becomes stable.

**Comment by haraldkoch** [comment]
ZFS 0.7.0 was released in July, and they're up to 0.7.4 now.

**Comment by ddevault** [comment]
Bump. Was unable to compile this against the latest libzfs.

**Comment by lorenz** [comment]
@SirCmpwn I have a working fork at https://github.com/lorenz/go-libzfs which works with ZoL 0.7. You could try to replace the dependency with my fork and see if it works.
